export const FILMS_SET_ACTIVE_PANEL = 'FILMS_SET_ACTIVE_PANEL';

export const FILMS_LIST_LOADER_SET = 'FILMS_LIST_LOADER_SET';
export const FILMS_LIST_LOADER_UNSET = 'FILMS_LIST_LOADER_UNSET';

export const FILMS_ONE_LOADER_SET = 'FILMS_ONE_LOADER_SET';
export const FILMS_ONE_LOADER_UNSET = 'FILMS_ONE_LOADER_UNSET';

export const FILMS_LIST_ERROR_SET = 'FILMS_LIST_ERROR_SET';
export const FILMS_LIST_ERROR_UNSET = 'FILMS_LIST_ERROR_UNSET';

export const FILMS_ONE_ERROR_SET = 'FILMS_ONE_ERROR_SET';
export const FILMS_ONE_ERROR_UNSET = 'FILMS_ONE_ERROR_UNSET';

export const FILMS_REQUEST_LIST = 'FILMS_REQUEST_LIST';
export const FILMS_REQUEST_ONE = 'FILMS_REQUEST_ONE';
export const FILMS_UPDATE_LIST = 'FILMS_UPDATE_LIST';
export const FILMS_UPDATE_ONE = 'FILMS_UPDATE_ONE';
